# Generated by Django 5.0.6 on 2024-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='Draft', max_length=20),
        ),
    ]
